[theme]
primaryColor = "#2563EB"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18181B"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
